[package]
name = "xcb"
version = "0.1.0"
authors = ["agares <me@agares.info>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "1.2.1"
[dependencies.xcb-system]
path="../xcb-system"